### ISSUE TITLE
Android back button override closes app

### ISSUE THREAD

**Issue by neilt6** [PrismLibrary/Prism.Maui#105]
The Android back button override from #88 isn't working properly on my end.

### Steps to Reproduce

1. Build and launch _PrismMauiDemo_ on an Android 10.0 emulator.
2. Click _Flyout Page_.
3. Click the _Back_ button on the emulator.

### Expected Behavior

- Navigation from _ViewD_ to _ViewC_:

```
[DOTNET] ViewD - View Disappearing
[DOTNET] ViewC - View Appearing
[DOTNET] ViewD - ViewModel NavigatedFrom
[DOTNET] ViewC - ViewModel NavigatedTo
[DOTNET] Navigation: GoBack
[DOTNET] Result: Success
```

### Observed Behavior

- The app closes, and all manner of badness ensues:

```
[DOTNET] ViewD - View Disappearing
[DOTNET] ViewC - View Appearing
[DOTNET] ViewC - View Disappearing
[DOTNET] ViewD - ViewModel NavigatedFrom
[DOTNET] ViewC - ViewModel NavigatedTo
[DOTNET] Navigation: GoBack
[DOTNET] Result: Success
[DOTNET] ViewC - ViewModel NavigatedFrom
[DOTNET] ViewB - ViewModel NavigatedTo
[DOTNET] Navigation: GoBack
[DOTNET] Result: Success
```

- Reopening the app from recent apps reveals _ViewB_ with no navigation bar:

`[DOTNET] ViewB - View Appearing`

- Reopening the app from the launcher throws an exception and crashes:

```
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NotImplementedException: Either set MainPage or override CreateWindow.
[mono-rt]    at Microsoft.Maui.Controls.Application.CreateWindow(IActivationState activationState) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Application\Application.Impl.cs:line 126
[mono-rt]    at Microsoft.Maui.Controls.Application.Microsoft.Maui.IApplication.CreateWindow(IActivationState activationState) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Application\Application.Impl.cs:line 40
[mono-rt]    at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Activity activity, IApplication application, Bundle savedInstanceState) in D:\a\_work\1\s\src\Core\src\Platform\Android\ApplicationExtensions.cs:line 44
[mono-rt]    at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState) in D:\a\_work\1\s\src\Core\src\Platform\Android\MauiAppCompatActivity.cs:line 32
[mono-rt]    at PrismMauiDemo.MainActivity.OnCreate(Bundle savedInstanceState) in C:\Users\NeilThiessen\Downloads\Prism.Maui-master\sample\PrismMauiDemo\Platforms\Android\MainActivity.cs:line 12
[mono-rt]    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Android.App.Activity.cs:line 2781
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 121
```

**Comment by sact1909** [comment]
it could be the same that is happening to me when I call the GoBackAsync, for some reason is closing the app and sometimes it says "Object no set as an Instance of an object", DON'T KNOW WHY... 

`await NavigationService.GoBackAsync();`
or
just using the Navigation Page back button
